
train_neg_sample_args: None
train_batch_size: 2048
eval_batch_size: 2048
learning_rate: 0.001
loss_type: 'CE'
num_layers: 2
num_heads: 2

metrics: ["Hit", "NDCG"]
topk: [10, 50]
valid_metric: 'NDCG@10'

hidden_size: 300
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'

item_drop_ratio: 0.2
item_drop_coefficient: 0.9
lambda: 1e-3


